import {
  Flower2,
  Sprout,
  Mountain,
  HardHat,
  Grid3x3,
  Waves,
  BrickWall,
  Hammer,
  Shovel,
  Ruler,
  PaintBucket,
  Drill,
  Warehouse,
  TreePine,
  Home,
  type LucideIcon,
} from "lucide-react";

export const calculatorIcons: Record<string, LucideIcon> = {
  mulch: Flower2,
  soil: Sprout,
  gravel: Mountain,
  sand: Waves,
  topsoil: Sprout,
  stone: Mountain,
  "river-rock": Mountain,
  "pea-gravel": Mountain,
  concrete: HardHat,
  pavers: Grid3x3,
  "crushed-stone": Mountain,
  limestone: Mountain,
  asphalt: HardHat,
  brick: BrickWall,
  "fill-dirt": Shovel,
};
